on:
  push:
  
jobs:
  kernel_build:
    name: Kernel Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build using bash
      run: |
        chmod +x build.sh
        ./build.sh
